### ISSUE TITLE
Github Action(CI/CD) 구성

### ISSUE THREAD

**Issue by ckstn0777** [bside14-05/Front#2]
## ✨ 어떤 기능인가요?
nextjs 애플리케이션을 배포하기 위한 CI/CD 구성

## ✅ TODOs
- [x] docker image 생성
- [x] github actions yml 작성
- [x] github secret 환경변수 설정
